baseURL = "https://athulcyriac.xyz/"
languageCode = "en-us"
title = "Athul Cyriac Ajay"
theme = "archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
enableEmoji = true
pygmentscodefencesguesssyntax = true

[params]
	mode="dark" # color-mode → light,dark or auto
	useCDN=true
	favicon = "https://github.com/athul.png"
	og_image = "https://file.coffee/u/zrbyj5l-Ek.png"
	sitename = "Athul's Personal website"
	description="Athul's Personal Website built with Hugo and Archie Theme"
[[menu.main]]
name = "Books"
url = "/books"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1

####

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"
